### ISSUE TITLE
scrypt

### ISSUE THREAD

**Issue by continue98** [Mellnik/hash-plugin#2]
Hi, my friend. I'll forgive you add the scrypt algorithm to this plugin. I hope that you will respond.
https://en.wikipedia.org/wiki/Scrypt

**Comment by Mellnik** [comment]
Hi,
this plugin uses the Crypto++ library (https://www.cryptopp.com/). It currently does not support scrypt. Though they have it on their roadmap (https://www.cryptopp.com/wiki/Roadmap).

**Comment by continue98** [comment]
Hi. scrypt add in 7.0.0 cryptopp. Go add in plugin?

**Comment by Mellnik** [comment]
Hey! Yeah, I will have a look.

**Comment by Mellnik** [comment]
What exactly do you need it for? The PBKDF2 implementation also provides a strong key derivation. Implementing scrypt will also require a threading model (like PBKDF2) if you don't want to block the servers main thread.
