### ISSUE TITLE
sampctl

### ISSUE THREAD

**Issue by BronzeCheese** [Mellnik/hash-plugin#3]
Hey hey! So I've been setting up sampctl for my gamemode and this is one of the plugins / includes I use that currently can't be used as a package in sampctl. Is there any chance you could add the pawn.json file needed for sampctl so that I could include this in my gamemode? I'd very much appreciate it!

**Comment by Mellnik** [comment]
Hi! To be honest I have no idea about sampctl. If someone can provide that file I would gladly add it to the repo.

**Comment by BronzeCheese** [comment]
Took me some time to figure it out how to do it, but judging by how other plugins have done it, the pawn.json I proposed should do it (once you approve it I'll test it and tell you if it worked).
